# Site settings
title: Masoud Rahimi
email: work.rahimi@gmail.com
url: https://masoudr.github.io
description: "Masoud Rahimi Personal Website."
keywords: "masoud rahimi, embedded systems engineer, backend developer"
skills: "Embedded Systems Engineer - Backend Developer"
meta_author: Rahimi Masoud

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Masoud Rahimi
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/masoudr
  - title: linkedin
    url: https://www.linkedin.com/in/masoud-rahimi-a20a35135
  - title: stack-overflow
    url: https://stackoverflow.com/users/story/6700019

# Postal address (add as many lines as necessary)
address:
  - line: Tehran Province, Iran

# Credits content
credits: 'Powered by <a href="https://jekyllrb.com">Jekyll</a> & <a href="https://jekyllthemes.io/theme/freelancer-theme">Freelancer theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty
